apiVersion: v1
kind: ConfigMap
metadata:
  name: chaoxing-config
  namespace: chaoxing
data:
  # 应用配置
  LOG_LEVEL: "INFO"
  DEBUG: "False"
  
  # 数据库配置（使用Secret中的密码）
  DATABASE_URL: "postgresql+asyncpg://chaoxing_user:PASSWORD@postgres:5432/chaoxing_db"
  
  # Redis配置
  REDIS_URL: "redis://:PASSWORD@redis:6379/0"
  CELERY_BROKER_URL: "redis://:PASSWORD@redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://:PASSWORD@redis:6379/0"

